### ISSUE TITLE
Sign-in is not working since 28/Jul/2023

### ISSUE THREAD

**Issue by Tink2Hack** [Hunter-How/Support#6]
Hi the signin is not wokring in any of the web and mobile browsers. It just pops up and stays as it is. 
<img width="1680" alt="Screenshot 2023-07-29 at 2 20 42 AM" src="https://github.com/Hunter-How/Support/assets/8475218/259a649d-a5d9-43eb-9f73-ff38065206d8">

**Comment by jt-hyperview** [comment]
I'm getting the same issue. I tried on multiple browsers on multiple endpoints.

**Comment by HowHunterHow** [comment]
We have fixed this issue on Sunday 29/JUL/2023. Please check that out. Thank you for your report~~

**Comment by DenTricky73** [comment]
Not working!

**Comment by HowHunterHow** [comment]
> Not working!
<img width="748" alt="Screen Shot 2024-09-30 at 13 15 56" src="https://github.com/user-attachments/assets/c77b3736-13dd-410f-852e-b71972338de7">
The login service is working.
Our login service uses Google accounts to verify identity. You need to ensure that your IP is in an area that supports Google identity verification services.

**Comment by HowHunterHow** [comment]
Fixed now, thank you for your notice
