### ISSUE TITLE
API Retruns invalid JSON

### ISSUE THREAD

**Issue by jamez01** [Hunter-How/Support#9]
## JSON returned from the API is invalid.

* Quotes in JSON are required to be double 
* All keys and values should be quoted.
  * In the example below, the 'data' key's value, 'None' is not quoted at all.
 
e.g.

### Actual response from API:
```json
{'code': 400, 'data': None, 'message': 'Exceed the daily query usage, try again tomorrow'}
```

### Still invalid even if everything was 'properly' quoted in single quotes:
```json
{'code': 400, 'data': 'None', 'message': 'Exceed the daily query usage, try again tomorrow'}
```

### Should be
```json
{"code": 400, "data": "None", "message": "Exceed the daily query usage, try again tomorrow"}
```

Some libraries may be able to work around this, but others can not. Here is an example of ruby being unable to parse either of the above invalid responses:

### Actual API Response
```ruby
irb(main):002> invalid_1 = "{'code': 400, 'data': None, 'message': 'Exceed the daily query usage, try again tomorrow'}"
=> "{'code': 400, 'data': None, 'message': 'Exceed the daily query usage, try again tomorrow'}"
irb(main):003> JSON.parse(invalid_1)
/home/james/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/json/common.rb:216:in `parse': unexpected token at '{'code': 400, 'data': None, 'message': 'Exceed the daily query usage, try again tomorrow'}' (JSON::ParserError)
	from /home/james/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/json/common.rb:216:in `parse'
	from (irb):3:in `<main>'
	from /home/james/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/irb-1.14.1/exe/irb:9:in `<top (required)>'
	from /home/james/.asdf/installs/ruby/3.2.1/bin/irb:25:in `load'
	from /home/james/.asdf/installs/ruby/3.2.1/bin/irb:25:in `<main>'
irb(main):004> invalid_2 = "{'code': 400, 'data': 'None', 'message': 'Exceed the daily query usage, try again tomorrow'}"
```
### Response if with all quotes single quoted
```ruby
=> "{'code': 400, 'data': 'None', 'message': 'Exceed the daily query usage, try again tomorrow'}"
irb(main):009> JSON.parse(invalid_2)
/home/james/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/json/common.rb:216:in `parse': unexpected token at '{'code': 400, 'data': 'None', 'message': 'Exceed the daily query usage, try again tomorrow'}' (JSON::ParserError)
	from /home/james/.asdf/installs/ruby/3.2.1/lib/ruby/3.2.0/json/common.rb:216:in `parse'
	from (irb):9:in `<main>'
	from /home/james/.asdf/installs/ruby/3.2.1/lib/ruby/gems/3.2.0/gems/irb-1.14.1/exe/irb:9:in `<top (required)>'
	from /home/james/.asdf/installs/ruby/3.2.1/bin/irb:25:in `load'
	from /home/james/.asdf/installs/ruby/3.2.1/bin/irb:25:in `<main>'
```

### Valid JSON

```ruby
irb(main):007> valid = '{"code": 400, "data": "None", "message": "Exceed the daily query usage, try again tomorrow"}'
=> "{\"code\": 400, \"data\": \"None\", \"message\": \"Exceed the daily query usage, try again tomorrow\"}"
irb(main):008> JSON.parse(valid)
=> {"code"=>400, "data"=>"None", "message"=>"Exceed the daily query usage, try again tomorrow"}
```

## Notes
I included all 3 examples because the API returns invalid JSON like the 2nd example if you do not get an API limit error.  JSON appears to be invalid throughout the entire API.

**Comment by HowHunterHow** [comment]
The original API response is: {"code":400,"data":null,"message":"xxxx"}. The format of responses depends on the language you use. The default response of JSON messages in Python uses single quotes. 
None is quoted which it means a null value in Python. It will not work if you copied the response from the Python script into Ruby to parse because the null value in Ruby is "nil", not "None". The value you parsed in the 3rd example with double quotes means the string "None" but not a null value. 
To resolve this issue, you can use Python to parse or use Ruby to make the request, try to avoid using different languages in two steps.
